FROM node:14.15.4-alpine3.10

RUN apk update && \
    apk upgrade && \
    apk --no-cache add --virtual builds-deps build-base python3

WORKDIR /usr/src/app

COPY ./package*.json ./

RUN npm install

EXPOSE 5000

CMD [ "npm", "start" ]
